package Hibernate;
// Generated 27 mars 2015 15:50:02 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Massnegotiation generated by hbm2java
 */
public class Massnegotiation  implements java.io.Serializable {


     private short numbernegmass;
     private Technology technology;
     private BigDecimal finalpercent;
     private BigDecimal temporarypercent;
     private Date entrydatemass;
     private String negomassstatus;
     private Date datevalidatemass;
     private Set<Proposepercent> proposepercents = new HashSet<Proposepercent>(0);
     private Set<Notifymass> notifymasses = new HashSet<Notifymass>(0);

    public Massnegotiation() {
    }

	
    public Massnegotiation(short numbernegmass, Technology technology) {
        this.numbernegmass = numbernegmass;
        this.technology = technology;
    }
    public Massnegotiation(short numbernegmass, Technology technology, BigDecimal finalpercent, BigDecimal temporarypercent, Date entrydatemass, String negomassstatus, Date datevalidatemass, Set<Proposepercent> proposepercents, Set<Notifymass> notifymasses) {
       this.numbernegmass = numbernegmass;
       this.technology = technology;
       this.finalpercent = finalpercent;
       this.temporarypercent = temporarypercent;
       this.entrydatemass = entrydatemass;
       this.negomassstatus = negomassstatus;
       this.datevalidatemass = datevalidatemass;
       this.proposepercents = proposepercents;
       this.notifymasses = notifymasses;
    }
   
    public short getNumbernegmass() {
        return this.numbernegmass;
    }
    
    public void setNumbernegmass(short numbernegmass) {
        this.numbernegmass = numbernegmass;
    }
    public Technology getTechnology() {
        return this.technology;
    }
    
    public void setTechnology(Technology technology) {
        this.technology = technology;
    }
    public BigDecimal getFinalpercent() {
        return this.finalpercent;
    }
    
    public void setFinalpercent(BigDecimal finalpercent) {
        this.finalpercent = finalpercent;
    }
    public BigDecimal getTemporarypercent() {
        return this.temporarypercent;
    }
    
    public void setTemporarypercent(BigDecimal temporarypercent) {
        this.temporarypercent = temporarypercent;
    }
    public Date getEntrydatemass() {
        return this.entrydatemass;
    }
    
    public void setEntrydatemass(Date entrydatemass) {
        this.entrydatemass = entrydatemass;
    }
    public String getNegomassstatus() {
        return this.negomassstatus;
    }
    
    public void setNegomassstatus(String negomassstatus) {
        this.negomassstatus = negomassstatus;
    }
    public Date getDatevalidatemass() {
        return this.datevalidatemass;
    }
    
    public void setDatevalidatemass(Date datevalidatemass) {
        this.datevalidatemass = datevalidatemass;
    }
    public Set<Proposepercent> getProposepercents() {
        return this.proposepercents;
    }
    
    public void setProposepercents(Set<Proposepercent> proposepercents) {
        this.proposepercents = proposepercents;
    }
    public Set<Notifymass> getNotifymasses() {
        return this.notifymasses;
    }
    
    public void setNotifymasses(Set<Notifymass> notifymasses) {
        this.notifymasses = notifymasses;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 67 * hash + this.numbernegmass;
        hash = 67 * hash + Objects.hashCode(this.technology);
        hash = 67 * hash + Objects.hashCode(this.finalpercent);
        hash = 67 * hash + Objects.hashCode(this.temporarypercent);
        hash = 67 * hash + Objects.hashCode(this.entrydatemass);
        hash = 67 * hash + Objects.hashCode(this.negomassstatus);
        hash = 67 * hash + Objects.hashCode(this.datevalidatemass);
        hash = 67 * hash + Objects.hashCode(this.proposepercents);
        hash = 67 * hash + Objects.hashCode(this.notifymasses);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Massnegotiation other = (Massnegotiation) obj;
        if (this.numbernegmass != other.numbernegmass) {
            return false;
        }
        if (!Objects.equals(this.technology, other.technology)) {
            return false;
        }
        if (!Objects.equals(this.finalpercent, other.finalpercent)) {
            return false;
        }
        if (!Objects.equals(this.temporarypercent, other.temporarypercent)) {
            return false;
        }
        if (!Objects.equals(this.entrydatemass, other.entrydatemass)) {
            return false;
        }
        if (!Objects.equals(this.negomassstatus, other.negomassstatus)) {
            return false;
        }
        if (!Objects.equals(this.datevalidatemass, other.datevalidatemass)) {
            return false;
        }
        if (!Objects.equals(this.proposepercents, other.proposepercents)) {
            return false;
        }
        if (!Objects.equals(this.notifymasses, other.notifymasses)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Massnegotiation{" + "numbernegmass=" + numbernegmass + ", technology=" + technology + ", finalpercent=" + finalpercent + ", temporarypercent=" + temporarypercent + ", entrydatemass=" + entrydatemass + ", negomassstatus=" + negomassstatus + ", datevalidatemass=" + datevalidatemass + ", proposepercents=" + proposepercents + ", notifymasses=" + notifymasses + '}';
    }




}


