package Hibernate;
// Generated 27 mars 2015 15:50:02 by Hibernate Tools 3.6.0

import java.util.Objects;




/**
 * Notifymass generated by hbm2java
 */
public class Notifymass  implements java.io.Serializable {


     private NotifymassId id;
     private Massnegotiation massnegotiation;
     private Users users;
     private String comstatusmass;
     private String percentstatus;
     private String newmassnego;

    public Notifymass() {
    }

	
    public Notifymass(NotifymassId id, Massnegotiation massnegotiation, Users users) {
        this.id = id;
        this.massnegotiation = massnegotiation;
        this.users = users;
    }
    public Notifymass(NotifymassId id, Massnegotiation massnegotiation, Users users, String comstatusmass, String percentstatus, String newmassnego) {
       this.id = id;
       this.massnegotiation = massnegotiation;
       this.users = users;
       this.comstatusmass = comstatusmass;
       this.percentstatus = percentstatus;
       this.newmassnego = newmassnego;
    }
   
    public NotifymassId getId() {
        return this.id;
    }
    
    public void setId(NotifymassId id) {
        this.id = id;
    }
    public Massnegotiation getMassnegotiation() {
        return this.massnegotiation;
    }
    
    public void setMassnegotiation(Massnegotiation massnegotiation) {
        this.massnegotiation = massnegotiation;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getComstatusmass() {
        return this.comstatusmass;
    }
    
    public void setComstatusmass(String comstatusmass) {
        this.comstatusmass = comstatusmass;
    }
    public String getPercentstatus() {
        return this.percentstatus;
    }
    
    public void setPercentstatus(String percentstatus) {
        this.percentstatus = percentstatus;
    }
    public String getNewmassnego() {
        return this.newmassnego;
    }
    
    public void setNewmassnego(String newmassnego) {
        this.newmassnego = newmassnego;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 67 * hash + Objects.hashCode(this.id);
        hash = 67 * hash + Objects.hashCode(this.massnegotiation);
        hash = 67 * hash + Objects.hashCode(this.users);
        hash = 67 * hash + Objects.hashCode(this.comstatusmass);
        hash = 67 * hash + Objects.hashCode(this.percentstatus);
        hash = 67 * hash + Objects.hashCode(this.newmassnego);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Notifymass other = (Notifymass) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        if (!Objects.equals(this.massnegotiation, other.massnegotiation)) {
            return false;
        }
        if (!Objects.equals(this.users, other.users)) {
            return false;
        }
        if (!Objects.equals(this.comstatusmass, other.comstatusmass)) {
            return false;
        }
        if (!Objects.equals(this.percentstatus, other.percentstatus)) {
            return false;
        }
        if (!Objects.equals(this.newmassnego, other.newmassnego)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Notifymass{" + "id=" + id + ", massnegotiation=" + massnegotiation + ", users=" + users + ", comstatusmass=" + comstatusmass + ", percentstatus=" + percentstatus + ", newmassnego=" + newmassnego + '}';
    }




}


