package Hibernate;
// Generated 27 mars 2015 15:50:02 by Hibernate Tools 3.6.0



/**
 * NotifymassId generated by hbm2java
 */
public class NotifymassId  implements java.io.Serializable {


     private String iduser;
     private short numbernegmass;

    public NotifymassId() {
    }

    public NotifymassId(String iduser, short numbernegmass) {
       this.iduser = iduser;
       this.numbernegmass = numbernegmass;
    }
   
    public String getIduser() {
        return this.iduser;
    }
    
    public void setIduser(String iduser) {
        this.iduser = iduser;
    }
    public short getNumbernegmass() {
        return this.numbernegmass;
    }
    
    public void setNumbernegmass(short numbernegmass) {
        this.numbernegmass = numbernegmass;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NotifymassId) ) return false;
		 NotifymassId castOther = ( NotifymassId ) other; 
         
		 return ( (this.getIduser()==castOther.getIduser()) || ( this.getIduser()!=null && castOther.getIduser()!=null && this.getIduser().equals(castOther.getIduser()) ) )
 && (this.getNumbernegmass()==castOther.getNumbernegmass());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIduser() == null ? 0 : this.getIduser().hashCode() );
         result = 37 * result + this.getNumbernegmass();
         return result;
   }   

    @Override
    public String toString() {
        return "NotifymassId{" + "iduser=" + iduser + ", numbernegmass=" + numbernegmass + '}';
    }


}


