package Hibernate;
// Generated 27 mars 2015 15:50:02 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Partnegotiation generated by hbm2java
 */
public class Partnegotiation  implements java.io.Serializable {


     private short numberneg;
     private Part part;
     private BigDecimal temporaryprice;
     private BigDecimal finalprice;
     private Date firstdate;
     private Short firstquantity;
     private Date entrydate;
     private String devises;
     private String negostatus;
     private Date datevalidate;
     private Date daterefuse;
     private Date datecancel;
     private Set<Notify> notifies = new HashSet<Notify>(0);
     private Set<Propose> proposes = new HashSet<Propose>(0);
     private Set<Post> posts = new HashSet<Post>(0);

    public Partnegotiation() {
    }

	
    public Partnegotiation(short numberneg, Part part) {
        this.numberneg = numberneg;
        this.part = part;
    }
    public Partnegotiation(short numberneg, Part part, BigDecimal temporaryprice, BigDecimal finalprice, Date firstdate, Short firstquantity, Date entrydate, String devises, String negostatus, Date datevalidate, Date daterefuse, Date datecancel, Set<Notify> notifies, Set<Propose> proposes, Set<Post> posts) {
       this.numberneg = numberneg;
       this.part = part;
       this.temporaryprice = temporaryprice;
       this.finalprice = finalprice;
       this.firstdate = firstdate;
       this.firstquantity = firstquantity;
       this.entrydate = entrydate;
       this.devises = devises;
       this.negostatus = negostatus;
       this.datevalidate = datevalidate;
       this.daterefuse = daterefuse;
       this.datecancel = datecancel;
       this.notifies = notifies;
       this.proposes = proposes;
       this.posts = posts;
    }
   
    public short getNumberneg() {
        return this.numberneg;
    }
    
    public void setNumberneg(short numberneg) {
        this.numberneg = numberneg;
    }
    public Part getPart() {
        return this.part;
    }
    
    public void setPart(Part part) {
        this.part = part;
    }
    public BigDecimal getTemporaryprice() {
        return this.temporaryprice;
    }
    
    public void setTemporaryprice(BigDecimal temporaryprice) {
        this.temporaryprice = temporaryprice;
    }
    public BigDecimal getFinalprice() {
        return this.finalprice;
    }
    
    public void setFinalprice(BigDecimal finalprice) {
        this.finalprice = finalprice;
    }
    public Date getFirstdate() {
        return this.firstdate;
    }
    
    public void setFirstdate(Date firstdate) {
        this.firstdate = firstdate;
    }
    public Short getFirstquantity() {
        return this.firstquantity;
    }
    
    public void setFirstquantity(Short firstquantity) {
        this.firstquantity = firstquantity;
    }
    public Date getEntrydate() {
        return this.entrydate;
    }
    
    public void setEntrydate(Date entrydate) {
        this.entrydate = entrydate;
    }
    public String getDevises() {
        return this.devises;
    }
    
    public void setDevises(String devises) {
        this.devises = devises;
    }
    public String getNegostatus() {
        return this.negostatus;
    }
    
    public void setNegostatus(String negostatus) {
        this.negostatus = negostatus;
    }
    public Date getDatevalidate() {
        return this.datevalidate;
    }
    
    public void setDatevalidate(Date datevalidate) {
        this.datevalidate = datevalidate;
    }
    public Date getDaterefuse() {
        return this.daterefuse;
    }
    
    public void setDaterefuse(Date daterefuse) {
        this.daterefuse = daterefuse;
    }
    public Date getDatecancel() {
        return this.datecancel;
    }
    
    public void setDatecancel(Date datecancel) {
        this.datecancel = datecancel;
    }
    public Set<Notify> getNotifies() {
        return this.notifies;
    }
    
    public void setNotifies(Set<Notify> notifies) {
        this.notifies = notifies;
    }
    public Set<Propose> getProposes() {
        return this.proposes;
    }
    
    public void setProposes(Set<Propose> proposes) {
        this.proposes = proposes;
    }
    public Set<Post> getPosts() {
        return this.posts;
    }
    
    public void setPosts(Set<Post> posts) {
        this.posts = posts;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 83 * hash + this.numberneg;
        hash = 83 * hash + Objects.hashCode(this.part);
        hash = 83 * hash + Objects.hashCode(this.temporaryprice);
        hash = 83 * hash + Objects.hashCode(this.finalprice);
        hash = 83 * hash + Objects.hashCode(this.firstdate);
        hash = 83 * hash + Objects.hashCode(this.firstquantity);
        hash = 83 * hash + Objects.hashCode(this.entrydate);
        hash = 83 * hash + Objects.hashCode(this.devises);
        hash = 83 * hash + Objects.hashCode(this.negostatus);
        hash = 83 * hash + Objects.hashCode(this.datevalidate);
        hash = 83 * hash + Objects.hashCode(this.daterefuse);
        hash = 83 * hash + Objects.hashCode(this.datecancel);
        hash = 83 * hash + Objects.hashCode(this.notifies);
        hash = 83 * hash + Objects.hashCode(this.proposes);
        hash = 83 * hash + Objects.hashCode(this.posts);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Partnegotiation other = (Partnegotiation) obj;
        if (this.numberneg != other.numberneg) {
            return false;
        }
        if (!Objects.equals(this.part, other.part)) {
            return false;
        }
        if (!Objects.equals(this.temporaryprice, other.temporaryprice)) {
            return false;
        }
        if (!Objects.equals(this.finalprice, other.finalprice)) {
            return false;
        }
        if (!Objects.equals(this.firstdate, other.firstdate)) {
            return false;
        }
        if (!Objects.equals(this.firstquantity, other.firstquantity)) {
            return false;
        }
        if (!Objects.equals(this.entrydate, other.entrydate)) {
            return false;
        }
        if (!Objects.equals(this.devises, other.devises)) {
            return false;
        }
        if (!Objects.equals(this.negostatus, other.negostatus)) {
            return false;
        }
        if (!Objects.equals(this.datevalidate, other.datevalidate)) {
            return false;
        }
        if (!Objects.equals(this.daterefuse, other.daterefuse)) {
            return false;
        }
        if (!Objects.equals(this.datecancel, other.datecancel)) {
            return false;
        }
        if (!Objects.equals(this.notifies, other.notifies)) {
            return false;
        }
        if (!Objects.equals(this.proposes, other.proposes)) {
            return false;
        }
        if (!Objects.equals(this.posts, other.posts)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Partnegotiation{" + "numberneg=" + numberneg + ", part=" + part + ", temporaryprice=" + temporaryprice + ", finalprice=" + finalprice + ", firstdate=" + firstdate + ", firstquantity=" + firstquantity + ", entrydate=" + entrydate + ", devises=" + devises + ", negostatus=" + negostatus + ", datevalidate=" + datevalidate + ", daterefuse=" + daterefuse + ", datecancel=" + datecancel + ", notifies=" + notifies + ", proposes=" + proposes + ", posts=" + posts + '}';
    }




}


