package Hibernate;
// Generated 27 mars 2015 15:50:02 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Positions generated by hbm2java
 */
public class Positions  implements java.io.Serializable {


     private byte idrole;
     private String labelrole;
     private String photo;
     private Set<Users> userses = new HashSet<Users>(0);

    public Positions() {
    }

	
    public Positions(byte idrole, String labelrole) {
        this.idrole = idrole;
        this.labelrole = labelrole;
    }
    public Positions(byte idrole, String labelrole, String photo, Set<Users> userses) {
       this.idrole = idrole;
       this.labelrole = labelrole;
       this.photo = photo;
       this.userses = userses;
    }
   
    public byte getIdrole() {
        return this.idrole;
    }
    
    public void setIdrole(byte idrole) {
        this.idrole = idrole;
    }
    public String getLabelrole() {
        return this.labelrole;
    }
    
    public void setLabelrole(String labelrole) {
        this.labelrole = labelrole;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public Set<Users> getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 29 * hash + this.idrole;
        hash = 29 * hash + Objects.hashCode(this.labelrole);
        hash = 29 * hash + Objects.hashCode(this.photo);
        hash = 29 * hash + Objects.hashCode(this.userses);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Positions other = (Positions) obj;
        if (this.idrole != other.idrole) {
            return false;
        }
        if (!Objects.equals(this.labelrole, other.labelrole)) {
            return false;
        }
        if (!Objects.equals(this.photo, other.photo)) {
            return false;
        }
        if (!Objects.equals(this.userses, other.userses)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Positions{" + "idrole=" + idrole + ", labelrole=" + labelrole + ", photo=" + photo + ", userses=" + userses + '}';
    }




}


