package Hibernate;
// Generated 27 mars 2015 15:50:02 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * ProposepercentId generated by hbm2java
 */
public class ProposepercentId  implements java.io.Serializable {


     private String iduser;
     private short numbernegmass;
     private Date datepercent;

    public ProposepercentId() {
    }

    public ProposepercentId(String iduser, short numbernegmass, Date datepercent) {
       this.iduser = iduser;
       this.numbernegmass = numbernegmass;
       this.datepercent = datepercent;
    }
   
    public String getIduser() {
        return this.iduser;
    }
    
    public void setIduser(String iduser) {
        this.iduser = iduser;
    }
    public short getNumbernegmass() {
        return this.numbernegmass;
    }
    
    public void setNumbernegmass(short numbernegmass) {
        this.numbernegmass = numbernegmass;
    }
    public Date getDatepercent() {
        return this.datepercent;
    }
    
    public void setDatepercent(Date datepercent) {
        this.datepercent = datepercent;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProposepercentId) ) return false;
		 ProposepercentId castOther = ( ProposepercentId ) other; 
         
		 return ( (this.getIduser()==castOther.getIduser()) || ( this.getIduser()!=null && castOther.getIduser()!=null && this.getIduser().equals(castOther.getIduser()) ) )
 && (this.getNumbernegmass()==castOther.getNumbernegmass())
 && ( (this.getDatepercent()==castOther.getDatepercent()) || ( this.getDatepercent()!=null && castOther.getDatepercent()!=null && this.getDatepercent().equals(castOther.getDatepercent()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIduser() == null ? 0 : this.getIduser().hashCode() );
         result = 37 * result + this.getNumbernegmass();
         result = 37 * result + ( getDatepercent() == null ? 0 : this.getDatepercent().hashCode() );
         return result;
   }   

    @Override
    public String toString() {
        return "ProposepercentId{" + "iduser=" + iduser + ", numbernegmass=" + numbernegmass + ", datepercent=" + datepercent + '}';
    }


}


