package Hibernate;
// Generated 27 mars 2015 15:50:02 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Technology generated by hbm2java
 */
public class Technology  implements java.io.Serializable {


     private String technocode;
     private String label;
     private Short cyclerealisation;
     private Integer industrialisationlot1;
     private Integer industrialisationlot2;
     private Integer industrialisationlot3;
     private Set<Part> parts = new HashSet<Part>(0);
     private Set<Massnegotiation> massnegotiations = new HashSet<Massnegotiation>(0);

    public Technology() {
    }

	
    public Technology(String technocode) {
        this.technocode = technocode;
    }
    public Technology(String technocode, String label, Short cyclerealisation, Integer industrialisationlot1, Integer industrialisationlot2, Integer industrialisationlot3, Set<Part> parts, Set<Massnegotiation> massnegotiations) {
       this.technocode = technocode;
       this.label = label;
       this.cyclerealisation = cyclerealisation;
       this.industrialisationlot1 = industrialisationlot1;
       this.industrialisationlot2 = industrialisationlot2;
       this.industrialisationlot3 = industrialisationlot3;
       this.parts = parts;
       this.massnegotiations = massnegotiations;
    }
   
    public String getTechnocode() {
        return this.technocode;
    }
    
    public void setTechnocode(String technocode) {
        this.technocode = technocode;
    }
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }
    public Short getCyclerealisation() {
        return this.cyclerealisation;
    }
    
    public void setCyclerealisation(Short cyclerealisation) {
        this.cyclerealisation = cyclerealisation;
    }
    public Integer getIndustrialisationlot1() {
        return this.industrialisationlot1;
    }
    
    public void setIndustrialisationlot1(Integer industrialisationlot1) {
        this.industrialisationlot1 = industrialisationlot1;
    }
    public Integer getIndustrialisationlot2() {
        return this.industrialisationlot2;
    }
    
    public void setIndustrialisationlot2(Integer industrialisationlot2) {
        this.industrialisationlot2 = industrialisationlot2;
    }
    public Integer getIndustrialisationlot3() {
        return this.industrialisationlot3;
    }
    
    public void setIndustrialisationlot3(Integer industrialisationlot3) {
        this.industrialisationlot3 = industrialisationlot3;
    }
    public Set<Part> getParts() {
        return this.parts;
    }
    
    public void setParts(Set<Part> parts) {
        this.parts = parts;
    }
    public Set<Massnegotiation> getMassnegotiations() {
        return this.massnegotiations;
    }
    
    public void setMassnegotiations(Set<Massnegotiation> massnegotiations) {
        this.massnegotiations = massnegotiations;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 73 * hash + Objects.hashCode(this.technocode);
        hash = 73 * hash + Objects.hashCode(this.label);
        hash = 73 * hash + Objects.hashCode(this.cyclerealisation);
        hash = 73 * hash + Objects.hashCode(this.industrialisationlot1);
        hash = 73 * hash + Objects.hashCode(this.industrialisationlot2);
        hash = 73 * hash + Objects.hashCode(this.industrialisationlot3);
        hash = 73 * hash + Objects.hashCode(this.parts);
        hash = 73 * hash + Objects.hashCode(this.massnegotiations);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Technology other = (Technology) obj;
        if (!Objects.equals(this.technocode, other.technocode)) {
            return false;
        }
        if (!Objects.equals(this.label, other.label)) {
            return false;
        }
        if (!Objects.equals(this.cyclerealisation, other.cyclerealisation)) {
            return false;
        }
        if (!Objects.equals(this.industrialisationlot1, other.industrialisationlot1)) {
            return false;
        }
        if (!Objects.equals(this.industrialisationlot2, other.industrialisationlot2)) {
            return false;
        }
        if (!Objects.equals(this.industrialisationlot3, other.industrialisationlot3)) {
            return false;
        }
        if (!Objects.equals(this.parts, other.parts)) {
            return false;
        }
        if (!Objects.equals(this.massnegotiations, other.massnegotiations)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Technology{" + "technocode=" + technocode + ", label=" + label + ", cyclerealisation=" + cyclerealisation + ", industrialisationlot1=" + industrialisationlot1 + ", industrialisationlot2=" + industrialisationlot2 + ", industrialisationlot3=" + industrialisationlot3 + ", parts=" + parts + ", massnegotiations=" + massnegotiations + '}';
    }




}


