package Hibernate;
// Generated 27 mars 2015 15:50:02 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private String iduser;
     private Company company;
     private String firstname;
     private String lastname;
     private String password;
     private String email;
     private String telephone;
     private Set<Positions> positionses = new HashSet<Positions>(0);
     private Set<Notifymass> notifymasses = new HashSet<Notifymass>(0);
     private Set<Proposepercent> proposepercents = new HashSet<Proposepercent>(0);
     private Set<Post> posts = new HashSet<Post>(0);
     private Set<Notify> notifies = new HashSet<Notify>(0);
     private Set<Propose> proposes = new HashSet<Propose>(0);

    public Users() {
    }

	
    public Users(String iduser, Company company, String password, String email) {
        this.iduser = iduser;
        this.company = company;
        this.password = password;
        this.email = email;
    }
    public Users(String iduser, Company company, String firstname, String lastname, String password, String email, String telephone, Set<Positions> positionses, Set<Notifymass> notifymasses, Set<Proposepercent> proposepercents, Set<Post> posts, Set<Notify> notifies, Set<Propose> proposes) {
       this.iduser = iduser;
       this.company = company;
       this.firstname = firstname;
       this.lastname = lastname;
       this.password = password;
       this.email = email;
       this.telephone = telephone;
       this.positionses = positionses;
       this.notifymasses = notifymasses;
       this.proposepercents = proposepercents;
       this.posts = posts;
       this.notifies = notifies;
       this.proposes = proposes;
    }
   
    public String getIduser() {
        return this.iduser;
    }
    
    public void setIduser(String iduser) {
        this.iduser = iduser;
    }
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public Set<Positions> getPositionses() {
        return this.positionses;
    }
    
    public void setPositionses(Set<Positions> positionses) {
        this.positionses = positionses;
    }
    public Set<Notifymass> getNotifymasses() {
        return this.notifymasses;
    }
    
    public void setNotifymasses(Set<Notifymass> notifymasses) {
        this.notifymasses = notifymasses;
    }
    public Set<Proposepercent> getProposepercents() {
        return this.proposepercents;
    }
    
    public void setProposepercents(Set<Proposepercent> proposepercents) {
        this.proposepercents = proposepercents;
    }
    public Set<Post> getPosts() {
        return this.posts;
    }
    
    public void setPosts(Set<Post> posts) {
        this.posts = posts;
    }
    public Set<Notify> getNotifies() {
        return this.notifies;
    }
    
    public void setNotifies(Set<Notify> notifies) {
        this.notifies = notifies;
    }
    public Set<Propose> getProposes() {
        return this.proposes;
    }
    
    public void setProposes(Set<Propose> proposes) {
        this.proposes = proposes;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 53 * hash + Objects.hashCode(this.iduser);
        hash = 53 * hash + Objects.hashCode(this.company);
        hash = 53 * hash + Objects.hashCode(this.firstname);
        hash = 53 * hash + Objects.hashCode(this.lastname);
        hash = 53 * hash + Objects.hashCode(this.password);
        hash = 53 * hash + Objects.hashCode(this.email);
        hash = 53 * hash + Objects.hashCode(this.telephone);
        hash = 53 * hash + Objects.hashCode(this.positionses);
        hash = 53 * hash + Objects.hashCode(this.notifymasses);
        hash = 53 * hash + Objects.hashCode(this.proposepercents);
        hash = 53 * hash + Objects.hashCode(this.posts);
        hash = 53 * hash + Objects.hashCode(this.notifies);
        hash = 53 * hash + Objects.hashCode(this.proposes);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Users other = (Users) obj;
        if (!Objects.equals(this.iduser, other.iduser)) {
            return false;
        }
        if (!Objects.equals(this.company, other.company)) {
            return false;
        }
        if (!Objects.equals(this.firstname, other.firstname)) {
            return false;
        }
        if (!Objects.equals(this.lastname, other.lastname)) {
            return false;
        }
        if (!Objects.equals(this.password, other.password)) {
            return false;
        }
        if (!Objects.equals(this.email, other.email)) {
            return false;
        }
        if (!Objects.equals(this.telephone, other.telephone)) {
            return false;
        }
        if (!Objects.equals(this.positionses, other.positionses)) {
            return false;
        }
        if (!Objects.equals(this.notifymasses, other.notifymasses)) {
            return false;
        }
        if (!Objects.equals(this.proposepercents, other.proposepercents)) {
            return false;
        }
        if (!Objects.equals(this.posts, other.posts)) {
            return false;
        }
        if (!Objects.equals(this.notifies, other.notifies)) {
            return false;
        }
        if (!Objects.equals(this.proposes, other.proposes)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Users{" + "iduser=" + iduser + ", company=" + company + ", firstname=" + firstname + ", lastname=" + lastname + ", password=" + password + ", email=" + email + ", telephone=" + telephone + ", positionses=" + positionses + ", notifymasses=" + notifymasses + ", proposepercents=" + proposepercents + ", posts=" + posts + ", notifies=" + notifies + ", proposes=" + proposes + '}';
    }




}


